import { User, Customer, Order, Design, Production, Payment, Attendance, Notification } from '@/types';

export const currentUser: User = {
  id: '1',
  email: 'admin@printsys.com',
  name: 'Nguyễn Văn Admin',
  role: 'admin',
};

export const mockUsers: User[] = [
  currentUser,
  { id: '2', email: 'cskh1@printsys.com', name: 'Trần Thị CSKH', role: 'cskh' },
  { id: '3', email: 'design1@printsys.com', name: 'Lê Văn Thiết kế', role: 'design' },
  { id: '4', email: 'prod1@printsys.com', name: 'Phạm Thị Sản xuất', role: 'production' },
  { id: '5', email: 'accounting1@printsys.com', name: 'Hoàng Văn Kế toán', role: 'accounting' },
  { id: '6', email: 'hr1@printsys.com', name: 'Võ Thị Nhân sự', role: 'hr' },
];

export const mockCustomers: Customer[] = [
  {
    id: 'c1',
    code: 'C001',
    name: 'Công ty TNHH ABC',
    taxCode: '0123456789',
    phone: '0901234567',
    address: '123 Nguyễn Huệ, Q.1, TP.HCM',
    folder: 'C001',
    createdAt: '2024-01-15',
    createdBy: 'Trần Thị CSKH',
  },
  {
    id: 'c2',
    code: 'T001',
    name: 'Cửa hàng XYZ',
    phone: '0912345678',
    address: '456 Lê Lợi, Q.3, TP.HCM',
    folder: 'T001',
    createdAt: '2024-02-20',
    createdBy: 'Trần Thị CSKH',
  },
  {
    id: 'c3',
    code: 'C002',
    name: 'Tập đoàn DEF',
    taxCode: '0987654321',
    phone: '0923456789',
    address: '789 Trần Hưng Đạo, Q.5, TP.HCM',
    folder: 'C002',
    createdAt: '2024-03-10',
    createdBy: 'Trần Thị CSKH',
  },
];

export const mockOrders: Order[] = [
  {
    id: 'o1',
    orderNumber: 'DH001',
    customerId: 'c1',
    customerName: 'Công ty TNHH ABC',
    description: 'In catalogue sản phẩm A4, 100 trang',
    quantity: 500,
    status: 'in_production',
    designStatus: 'approved',
    totalAmount: 15000000,
    depositAmount: 7500000,
    depositPaid: true,
    deliveryAddress: '123 Nguyễn Huệ, Q.1, TP.HCM',
    deliveryDate: '2024-12-30',
    createdAt: '2024-10-15',
    createdBy: 'Trần Thị CSKH',
  },
  {
    id: 'o2',
    orderNumber: 'DH002',
    customerId: 'c2',
    customerName: 'Cửa hàng XYZ',
    description: 'In brochure quảng cáo A5',
    quantity: 1000,
    status: 'waiting_deposit',
    designStatus: 'approved',
    totalAmount: 8000000,
    depositAmount: 4000000,
    depositPaid: false,
    deliveryAddress: '456 Lê Lợi, Q.3, TP.HCM',
    deliveryDate: '2024-12-25',
    createdAt: '2024-10-20',
    createdBy: 'Trần Thị CSKH',
  },
  {
    id: 'o3',
    orderNumber: 'DH003',
    customerId: 'c3',
    customerName: 'Tập đoàn DEF',
    description: 'In hộp giấy cao cấp',
    quantity: 2000,
    status: 'designing',
    designStatus: 'in_progress',
    totalAmount: 25000000,
    depositPaid: false,
    deliveryAddress: '789 Trần Hưng Đạo, Q.5, TP.HCM',
    deliveryDate: '2025-01-10',
    createdAt: '2024-10-25',
    createdBy: 'Trần Thị CSKH',
  },
  {
    id: 'o4',
    orderNumber: 'DH004',
    customerId: 'c1',
    customerName: 'Công ty TNHH ABC',
    description: 'In name card cao cấp',
    quantity: 500,
    status: 'new',
    designStatus: 'pending',
    depositPaid: false,
    deliveryAddress: '123 Nguyễn Huệ, Q.1, TP.HCM',
    createdAt: '2024-10-26',
    createdBy: 'Trần Thị CSKH',
  },
];

export const mockDesigns: Design[] = [
  {
    id: 'd1',
    orderId: 'o1',
    orderNumber: 'DH001',
    customerName: 'Công ty TNHH ABC',
    files: [
      {
        id: 'f1',
        name: 'catalogue-design-v1.pdf',
        url: '#',
        uploadedAt: '2024-10-16',
        uploadedBy: 'Lê Văn Thiết kế',
      },
      {
        id: 'f2',
        name: 'catalogue-design-final.pdf',
        url: '#',
        uploadedAt: '2024-10-18',
        uploadedBy: 'Lê Văn Thiết kế',
      },
    ],
    status: 'approved',
    notes: 'Khách hàng đã duyệt thiết kế phiên bản cuối',
    createdAt: '2024-10-16',
    updatedAt: '2024-10-18',
  },
  {
    id: 'd2',
    orderId: 'o2',
    orderNumber: 'DH002',
    customerName: 'Cửa hàng XYZ',
    files: [
      {
        id: 'f3',
        name: 'brochure-design-v1.ai',
        url: '#',
        uploadedAt: '2024-10-21',
        uploadedBy: 'Lê Văn Thiết kế',
      },
    ],
    status: 'approved',
    createdAt: '2024-10-21',
    updatedAt: '2024-10-22',
  },
  {
    id: 'd3',
    orderId: 'o3',
    orderNumber: 'DH003',
    customerName: 'Tập đoàn DEF',
    files: [],
    status: 'in_progress',
    notes: 'Đang thiết kế theo yêu cầu khách hàng',
    createdAt: '2024-10-25',
    updatedAt: '2024-10-25',
  },
];

export const mockProductions: Production[] = [
  {
    id: 'p1',
    orderId: 'o1',
    orderNumber: 'DH001',
    customerName: 'Công ty TNHH ABC',
    assignedTo: 'Phạm Thị Sản xuất',
    status: 'in_progress',
    progress: 60,
    notes: 'Đang in đợt 2/3',
    startedAt: '2024-10-19',
  },
  {
    id: 'p2',
    orderId: 'o2',
    orderNumber: 'DH002',
    customerName: 'Cửa hàng XYZ',
    status: 'pending',
    progress: 0,
    notes: 'Chờ kế toán xác nhận tiền cọc',
    startedAt: undefined,
  },
];

export const mockPayments: Payment[] = [
  {
    id: 'pay1',
    orderId: 'o1',
    orderNumber: 'DH001',
    customerName: 'Công ty TNHH ABC',
    amount: 7500000,
    type: 'deposit',
    status: 'paid',
    paidAt: '2024-10-17',
    notes: 'Đã thanh toán tiền cọc 50%',
    createdAt: '2024-10-17',
  },
  {
    id: 'pay2',
    orderId: 'o2',
    orderNumber: 'DH002',
    customerName: 'Cửa hàng XYZ',
    amount: 4000000,
    type: 'deposit',
    status: 'pending',
    notes: 'Chờ khách thanh toán tiền cọc',
    createdAt: '2024-10-22',
  },
  {
    id: 'pay3',
    orderId: 'o1',
    orderNumber: 'DH001',
    customerName: 'Công ty TNHH ABC',
    amount: 7500000,
    type: 'final',
    status: 'pending',
    notes: 'Thanh toán phần còn lại khi giao hàng',
    createdAt: '2024-10-19',
  },
];

export const mockAttendance: Attendance[] = [
  {
    id: 'a1',
    userId: '4',
    userName: 'Phạm Thị Sản xuất',
    date: '2024-10-26',
    checkIn: '08:00',
    checkOut: '17:30',
    status: 'present',
    workHours: 8.5,
    overtimeHours: 0.5,
  },
  {
    id: 'a2',
    userId: '3',
    userName: 'Lê Văn Thiết kế',
    date: '2024-10-26',
    checkIn: '08:15',
    checkOut: '17:00',
    status: 'late',
    workHours: 8,
    overtimeHours: 0,
    notes: 'Đến trễ 15 phút',
  },
  {
    id: 'a3',
    userId: '2',
    userName: 'Trần Thị CSKH',
    date: '2024-10-26',
    checkIn: '08:00',
    checkOut: '17:00',
    status: 'present',
    workHours: 8,
    overtimeHours: 0,
  },
];

export const mockNotifications: Notification[] = [
  {
    id: 'n1',
    type: 'warning',
    title: 'Đơn hàng sắp đến hạn giao',
    message: 'Đơn hàng DH001 sẽ đến hạn giao vào ngày 30/12/2024',
    relatedId: 'o1',
    relatedType: 'order',
    read: false,
    createdAt: '2024-10-26T08:00:00',
  },
  {
    id: 'n2',
    type: 'error',
    title: 'Đơn hàng chờ thanh toán quá lâu',
    message: 'Đơn hàng DH002 đã chờ thanh toán tiền cọc 4 ngày',
    relatedId: 'o2',
    relatedType: 'order',
    read: false,
    createdAt: '2024-10-26T09:00:00',
  },
  {
    id: 'n3',
    type: 'success',
    title: 'Thiết kế đã được duyệt',
    message: 'Thiết kế đơn hàng DH001 đã được khách hàng duyệt',
    relatedId: 'o1',
    relatedType: 'order',
    read: true,
    createdAt: '2024-10-25T14:30:00',
  },
];
