import { User, Customer, Order, Design, Production, Payment, Attendance, Notification } from '@/types';
export * from './mockData/inventory';

export const currentUser: User = {
  id: '1',
  email: 'admin@printsys.com',
  name: 'Nguyễn Văn Admin',
  role: 'admin',
};

export const mockUsers: User[] = [
  currentUser,
  { id: '2', email: 'cskh1@printsys.com', name: 'Trần Thị CSKH', role: 'cskh' },
  { id: '3', email: 'design1@printsys.com', name: 'Lê Văn Thiết kế', role: 'design' },
  { id: '4', email: 'prod1@printsys.com', name: 'Phạm Thị Sản xuất', role: 'production' },
  { id: '5', email: 'accounting1@printsys.com', name: 'Hoàng Văn Kế toán', role: 'accounting' },
  { id: '6', email: 'hr1@printsys.com', name: 'Võ Thị Nhân sự', role: 'hr' },
];

export const mockCustomers: Customer[] = [
  {
    id: 'c1',
    code: '0001MP',
    companyName: 'Công ty TNHH ABC Technology',
    representativeName: 'Nguyễn Minh Phúc',
    taxCode: '0123456789',
    phone: '0901234567',
    address: '123 Nguyễn Huệ, Phường Bến Nghé, Quận 1, TP.HCM',
    folder: '0001MP',
    createdAt: '2024-01-15',
    createdBy: 'Trần Thị CSKH',
  },
  {
    id: 'c2',
    code: '0002XQ',
    companyName: 'Cửa hàng XYZ Fashion',
    representativeName: 'Ngô Xuân Quý',
    taxCode: '0234567890',
    phone: '0912345678',
    address: '456 Lê Lợi, Phường Bến Thành, Quận 1, TP.HCM',
    folder: '0002XQ',
    createdAt: '2024-02-20',
    createdBy: 'Trần Thị CSKH',
  },
  {
    id: 'c3',
    code: '0003VD',
    companyName: 'Tập đoàn DEF Corporation',
    representativeName: 'Lê Văn Đức',
    taxCode: '0345678901',
    phone: '0923456789',
    address: '789 Trần Hưng Đạo, Phường Cầu Ông Lãnh, Quận 1, TP.HCM',
    folder: '0003VD',
    createdAt: '2024-03-10',
    createdBy: 'Trần Thị CSKH',
  },
  {
    id: 'c4',
    code: '0004TH',
    companyName: 'Nhà hàng Golden Star',
    representativeName: 'Phạm Thị Hương',
    taxCode: '0456789012',
    phone: '0934567890',
    address: '321 Nguyễn Văn Cừ, Phường Nguyễn Cư Trinh, Quận 1, TP.HCM',
    folder: '0004TH',
    createdAt: '2024-03-25',
    createdBy: 'Trần Thị CSKH',
  },
  {
    id: 'c5',
    code: '0005HA',
    companyName: 'Trường THPT Nguyễn Du',
    representativeName: 'Trần Hồng Anh',
    taxCode: '0567890123',
    phone: '0945678901',
    address: '654 Điện Biên Phủ, Phường 25, Quận Bình Thạnh, TP.HCM',
    folder: '0005HA',
    createdAt: '2024-04-05',
    createdBy: 'Trần Thị CSKH',
  },
  {
    id: 'c6',
    code: '0006BL',
    companyName: 'Phòng khám Đa khoa An Khang',
    representativeName: 'Võ Bảo Long',
    taxCode: '0678901234',
    phone: '0956789012',
    address: '987 Cách Mạng Tháng Tám, Phường 5, Quận Tân Bình, TP.HCM',
    folder: '0006BL',
    createdAt: '2024-04-20',
    createdBy: 'Trần Thị CSKH',
  },
  {
    id: 'c7',
    code: '0007QT',
    companyName: 'Công ty CP Kiến trúc Xanh',
    representativeName: 'Hoàng Quốc Tuấn',
    taxCode: '0789012345',
    phone: '0967890123',
    address: '147 Lý Tự Trọng, Phường Bến Nghé, Quận 1, TP.HCM',
    folder: '0007QT',
    createdAt: '2024-05-10',
    createdBy: 'Trần Thị CSKH',
  },
  {
    id: 'c8',
    code: '0008TL',
    representativeName: 'Đặng Thùy Linh', // Cá nhân (không có tên công ty)
    phone: '0978901234',
    address: '258 Pasteur, Phường 8, Quận 3, TP.HCM',
    folder: '0008TL',
    createdAt: '2024-05-25',
    createdBy: 'Trần Thị CSKH',
  },
  {
    id: 'c9',
    code: '0009NL',
    companyName: 'Doanh nghiệp tư nhân Minh Châu',
    representativeName: 'Nguyễn Thanh Long',
    taxCode: '0890123456',
    phone: '0989012345',
    address: '159 Võ Văn Tần, Phường 6, Quận 3, TP.HCM',
    folder: '0009NL',
    createdAt: '2024-06-01',
    createdBy: 'Trần Thị CSKH',
  },
];

export const mockOrders: Order[] = [
  {
    id: 'o1',
    orderNumber: 'DH001',
    customerId: 'c1',
    customerName: 'Công ty TNHH ABC Technology',
    description: 'In catalogue sản phẩm A4, 100 trang, giấy couche 150gsm, in 4 màu offset',
    quantity: 500,
    status: 'in_production',
    designStatus: 'approved',
    totalAmount: 15000000,
    depositAmount: 7500000,
    depositPaid: true,
    deliveryAddress: '123 Nguyễn Huệ, Phường Bến Nghé, Quận 1, TP.HCM',
    deliveryDate: '2024-12-30',
    createdAt: '2024-10-15',
    createdBy: 'Trần Thị CSKH',
  },
  {
    id: 'o2',
    orderNumber: 'DH002',
    customerId: 'c2',
    customerName: 'Cửa hàng XYZ Fashion',
    description: 'In brochure quảng cáo A5, gấp 3 lần, giấy art 130gsm',
    quantity: 1000,
    status: 'waiting_deposit',
    designStatus: 'approved',
    totalAmount: 8000000,
    depositAmount: 4000000,
    depositPaid: false,
    deliveryAddress: '456 Lê Lợi, Phường Bến Thành, Quận 1, TP.HCM',
    deliveryDate: '2024-12-25',
    createdAt: '2024-10-20',
    createdBy: 'Trần Thị CSKH',
  },
  {
    id: 'o3',
    orderNumber: 'DH003',
    customerId: 'c3',
    customerName: 'Tập đoàn DEF Corporation',
    description: 'In hộp giấy cao cấp, kích thước 20x15x10cm, giấy duplex 350gsm, cán màng bóng',
    quantity: 2000,
    status: 'designing',
    designStatus: 'in_progress',
    totalAmount: 25000000,
    depositPaid: false,
    deliveryAddress: '789 Trần Hưng Đạo, Phường Cầu Ông Lãnh, Quận 1, TP.HCM',
    deliveryDate: '2025-01-10',
    createdAt: '2024-10-25',
    createdBy: 'Trần Thị CSKH',
  },
  {
    id: 'o4',
    orderNumber: 'DH004',
    customerId: 'c1',
    customerName: 'Công ty TNHH ABC Technology',
    description: 'In name card cao cấp, giấy bristol 300gsm, tráng UV spot',
    quantity: 500,
    status: 'new',
    designStatus: 'pending',
    totalAmount: 3500000,
    depositPaid: false,
    deliveryAddress: '123 Nguyễn Huệ, Phường Bến Nghé, Quận 1, TP.HCM',
    deliveryDate: '2024-12-20',
    createdAt: '2024-10-26',
    createdBy: 'Trần Thị CSKH',
  },
  {
    id: 'o5',
    orderNumber: 'DH005',
    customerId: 'c4',
    customerName: 'Nhà hàng Golden Star',
    description: 'In menu thực đơn A4, giấy couche 200gsm, cán màng mờ',
    quantity: 100,
    status: 'completed',
    designStatus: 'approved',
    totalAmount: 2500000,
    depositAmount: 1250000,
    depositPaid: true,
    deliveryAddress: '321 Nguyễn Văn Cừ, Phường Nguyễn Cư Trinh, Quận 1, TP.HCM',
    deliveryDate: '2024-10-28',
    createdAt: '2024-10-10',
    createdBy: 'Trần Thị CSKH',
  },
  {
    id: 'o6',
    orderNumber: 'DH006',
    customerId: 'c5',
    customerName: 'Trường THPT Nguyễn Du',
    description: 'In banner tuyển sinh 3x2m, bạt hiflex 440gsm, kẻo viền',
    quantity: 5,
    status: 'waiting_approval',
    designStatus: 'waiting_approval',
    totalAmount: 1500000,
    depositPaid: false,
    deliveryAddress: '654 Điện Biên Phủ, Phường 25, Quận Bình Thạnh, TP.HCM',
    deliveryDate: '2024-12-15',
    createdAt: '2024-10-22',
    createdBy: 'Trần Thị CSKH',
  },
  {
    id: 'o7',
    orderNumber: 'DH007',
    customerId: 'c6',
    customerName: 'Phòng khám Đa khoa An Khang',
    description: 'In tờ rơi A5, giấy ford 100gsm, in 2 mặt 4 màu',
    quantity: 5000,
    status: 'designing',
    designStatus: 'in_progress',
    totalAmount: 12000000,
    depositAmount: 6000000,
    depositPaid: false,
    deliveryAddress: '987 Cách Mạng Tháng Tám, Phường 5, Quận Tân Bình, TP.HCM',
    deliveryDate: '2025-01-05',
    createdAt: '2024-10-24',
    createdBy: 'Trần Thị CSKH',
  },
  {
    id: 'o8',
    orderNumber: 'DH008',
    customerId: 'c7',
    customerName: 'Công ty CP Kiến trúc Xanh',
    description: 'In túi giấy kraft, kích thước 30x25x8cm, dây xách PP',
    quantity: 1000,
    status: 'in_production',
    designStatus: 'approved',
    totalAmount: 18000000,
    depositAmount: 9000000,
    depositPaid: true,
    deliveryAddress: '147 Lý Tự Trọng, Phường Bến Nghé, Quận 1, TP.HCM',
    deliveryDate: '2024-12-28',
    createdAt: '2024-10-18',
    createdBy: 'Trần Thị CSKH',
  },
];

export const mockDesigns: Design[] = [
  {
    id: 'd1',
    orderId: 'o1',
    orderNumber: 'DH001',
    customerName: 'Công ty TNHH ABC',
    files: [
      {
        id: 'f1',
        name: 'catalogue-design-v1.pdf',
        url: '#',
        uploadedAt: '2024-10-16',
        uploadedBy: 'Lê Văn Thiết kế',
      },
      {
        id: 'f2',
        name: 'catalogue-design-final.pdf',
        url: '#',
        uploadedAt: '2024-10-18',
        uploadedBy: 'Lê Văn Thiết kế',
      },
    ],
    status: 'approved',
    notes: 'Khách hàng đã duyệt thiết kế phiên bản cuối',
    createdAt: '2024-10-16',
    updatedAt: '2024-10-18',
  },
  {
    id: 'd2',
    orderId: 'o2',
    orderNumber: 'DH002',
    customerName: 'Cửa hàng XYZ',
    files: [
      {
        id: 'f3',
        name: 'brochure-design-v1.ai',
        url: '#',
        uploadedAt: '2024-10-21',
        uploadedBy: 'Lê Văn Thiết kế',
      },
    ],
    status: 'approved',
    createdAt: '2024-10-21',
    updatedAt: '2024-10-22',
  },
  {
    id: 'd3',
    orderId: 'o3',
    orderNumber: 'DH003',
    customerName: 'Tập đoàn DEF',
    files: [],
    status: 'in_progress',
    notes: 'Đang thiết kế theo yêu cầu khách hàng',
    createdAt: '2024-10-25',
    updatedAt: '2024-10-25',
  },
];

export const mockProductions: Production[] = [
  {
    id: 'p1',
    orderId: 'o1',
    orderNumber: 'DH001',
    customerName: 'Công ty TNHH ABC',
    assignedTo: 'Phạm Thị Sản xuất',
    status: 'in_progress',
    progress: 60,
    notes: 'Đang in đợt 2/3',
    startedAt: '2024-10-19',
  },
  {
    id: 'p2',
    orderId: 'o2',
    orderNumber: 'DH002',
    customerName: 'Cửa hàng XYZ',
    status: 'pending',
    progress: 0,
    notes: 'Chờ kế toán xác nhận tiền cọc',
    startedAt: undefined,
  },
];

export const mockPayments: Payment[] = [
  {
    id: 'pay1',
    orderId: 'o1',
    orderNumber: 'DH001',
    customerName: 'Công ty TNHH ABC',
    amount: 7500000,
    type: 'deposit',
    status: 'paid',
    paidAt: '2024-10-17',
    notes: 'Đã thanh toán tiền cọc 50%',
    createdAt: '2024-10-17',
  },
  {
    id: 'pay2',
    orderId: 'o2',
    orderNumber: 'DH002',
    customerName: 'Cửa hàng XYZ',
    amount: 4000000,
    type: 'deposit',
    status: 'pending',
    notes: 'Chờ khách thanh toán tiền cọc',
    createdAt: '2024-10-22',
  },
  {
    id: 'pay3',
    orderId: 'o1',
    orderNumber: 'DH001',
    customerName: 'Công ty TNHH ABC',
    amount: 7500000,
    type: 'final',
    status: 'pending',
    notes: 'Thanh toán phần còn lại khi giao hàng',
    createdAt: '2024-10-19',
  },
];

export const mockAttendance: Attendance[] = [
  {
    id: 'a1',
    userId: '4',
    userName: 'Phạm Thị Sản xuất',
    date: '2024-10-26',
    checkIn: '08:00',
    checkOut: '17:30',
    status: 'present',
    workHours: 8.5,
    overtimeHours: 0.5,
  },
  {
    id: 'a2',
    userId: '3',
    userName: 'Lê Văn Thiết kế',
    date: '2024-10-26',
    checkIn: '08:15',
    checkOut: '17:00',
    status: 'late',
    workHours: 8,
    overtimeHours: 0,
    notes: 'Đến trễ 15 phút',
  },
  {
    id: 'a3',
    userId: '2',
    userName: 'Trần Thị CSKH',
    date: '2024-10-26',
    checkIn: '08:00',
    checkOut: '17:00',
    status: 'present',
    workHours: 8,
    overtimeHours: 0,
  },
];

export const mockNotifications: Notification[] = [
  {
    id: 'n1',
    type: 'warning',
    title: 'Đơn hàng sắp đến hạn giao',
    message: 'Đơn hàng DH001 sẽ đến hạn giao vào ngày 30/12/2024',
    relatedId: 'o1',
    relatedType: 'order',
    read: false,
    createdAt: '2024-10-26T08:00:00',
  },
  {
    id: 'n2',
    type: 'error',
    title: 'Đơn hàng chờ thanh toán quá lâu',
    message: 'Đơn hàng DH002 đã chờ thanh toán tiền cọc 4 ngày',
    relatedId: 'o2',
    relatedType: 'order',
    read: false,
    createdAt: '2024-10-26T09:00:00',
  },
  {
    id: 'n3',
    type: 'success',
    title: 'Thiết kế đã được duyệt',
    message: 'Thiết kế đơn hàng DH001 đã được khách hàng duyệt',
    relatedId: 'o1',
    relatedType: 'order',
    read: true,
    createdAt: '2024-10-25T14:30:00',
  },
];

// Aliased exports for dashboard
export const orders = mockOrders;
export const customers = mockCustomers;
export const payments = mockPayments;
export const productions = mockProductions;
