const fs = require('fs');
const path = require('path');

const filePath = path.resolve(__dirname, 'src/pages/prepress/PrepressDetail.tsx');

const content = fs.readFileSync(filePath, 'utf8');
const lines = content.split(/\r?\n/);

console.log('Original total lines:', lines.length);

// Keep lines 1-1987 (index 0-1986) - includes ALL imports, state, handlers, loading/error returns
const keepLines = lines.slice(0, 1987);

// New return block using extracted components - replaces lines 1988-end
const newReturnLines = [
  '',
  '  return (',
  '    <div className="relative h-full flex flex-col overflow-hidden bg-background p-4">',
  '      {/* File Label for Debugging */}',
  '      <div className="absolute top-1 right-4 bg-rose-600 text-white text-[10px] px-1.5 py-0.5 rounded shadow-sm z-[100] font-mono pointer-events-none opacity-80">',
  '        PrepressDetail.tsx',
  '      </div>',
  '',
  '      {/* Header */}',
  '      <DetailHeader',
  '        order={order}',
  '        isEmptyOrder={isEmptyOrder}',
  '        hasDieCutDesigns={hasDieCutDesigns}',
  '        nextStatusInfo={nextStatusInfo}',
  '        canMarkCompleted={canMarkCompleted}',
  '        completionMissingItems={completionMissingItems}',
  '        navigate={navigate}',
  '        setIsDieListDialogOpen={setIsDieListDialogOpen}',
  '        setIsUploadDialogOpen={setIsUploadDialogOpen}',
  '        handleStatusChangeClick={handleStatusChangeClick}',
  '        handleOldStatusChangeClick={handleOldStatusChangeClick}',
  '      />',
  '',
  '      <div className="flex-1 flex flex-col min-h-0 overflow-hidden">',
  '        {isEmptyOrder ? (',
  '          <DetailEmptyOrderView',
  '            order={order}',
  '            designTypeOptions={designTypeOptions}',
  '            availableDesignsData={availableDesignsData}',
  '            selectedDesignTypes={selectedDesignTypes}',
  '            selectedMaterialTypes={selectedMaterialTypes}',
  '            currentMaterialTypeId={currentMaterialTypeId}',
  '            currentMaterialTypeName={currentMaterialTypeName}',
  '            searchTerm={searchTerm}',
  '            setSelectedDesignTypes={setSelectedDesignTypes}',
  '            setSelectedMaterialTypes={setSelectedMaterialTypes}',
  '            setSearchTerm={setSearchTerm}',
  '            handleClearFilters={handleClearFilters}',
  '            handleClearSelection={handleClearSelection}',
  '            isLoadingDesigns={isLoadingDesigns}',
  '            paginatedDesigns={paginatedDesigns}',
  '            groupByOrder={groupByOrder}',
  '            groupedByOrder={groupedByOrder}',
  '            selectedIds={selectedIds}',
  '            canSelect={canSelect}',
  '            toggleSelection={toggleSelection}',
  '            totalCount={totalCount}',
  '            currentPage={currentPage}',
  '            totalPages={totalPages}',
  '            pageInput={pageInput}',
  '            itemsPerPage={itemsPerPage}',
  '            handlePreviousPage={handlePreviousPage}',
  '            handleNextPage={handleNextPage}',
  '            handlePageInputChange={handlePageInputChange}',
  '            handlePageInputBlur={handlePageInputBlur}',
  '            tableContainerRef={tableContainerRef}',
  '            selectedDesigns={selectedDesigns}',
  '            selectedCount={selectedCount}',
  '            materialTypeName={materialTypeName}',
  '            designQuantities={designQuantities}',
  '            handleQuantityChange={handleQuantityChange}',
  '            paperSizes={paperSizes}',
  '            paperSizeId={paperSizeId}',
  '            setPaperSizeId={setPaperSizeId}',
  '            customPaperSize={customPaperSize}',
  '            setCustomPaperSize={setCustomPaperSize}',
  '            showCreateButton={showCreateButton}',
  '            existingPaperSize={existingPaperSize}',
  '            handleCreatePaperSize={handleCreatePaperSize}',
  '            isCreatingPaperSize={isCreatingPaperSize}',
  '            proofingSheetQuantity={proofingSheetQuantity}',
  '            setProofingSheetQuantity={setProofingSheetQuantity}',
  '            notes={notes}',
  '            setNotes={setNotes}',
  '            handleSubmitDesigns={handleSubmitDesigns}',
  '            isAddingDesigns={isAddingDesigns}',
  '            hasValidQuantities={hasValidQuantities}',
  '          />',
  '        ) : (',
  '          <div className="flex-1 flex flex-col gap-4 overflow-y-auto pb-4">',
  '            <DetailOrderInfoCard',
  '              order={order}',
  '              paperSizes={paperSizes}',
  '              updatePaperSizeId={updatePaperSizeId}',
  '              setUpdatePaperSizeId={setUpdatePaperSizeId}',
  '              updateCustomPaperSize={updateCustomPaperSize}',
  '              setUpdateCustomPaperSize={setUpdateCustomPaperSize}',
  '              existingUpdatePaperSize={existingUpdatePaperSize}',
  '              parsedUpdateCustomPaperSize={parsedUpdateCustomPaperSize}',
  '              isCreatingPaperSize={isCreatingPaperSize}',
  '              handleCreatePaperSize={handleCreatePaperSize}',
  '              isQuantityEditOpen={isQuantityEditOpen}',
  '              setIsQuantityEditOpen={setIsQuantityEditOpen}',
  '              updateStatus={updateStatus}',
  '              setUpdateStatus={setUpdateStatus}',
  '              updateNotes={updateNotes}',
  '              setUpdateNotes={setUpdateNotes}',
  '              updateProofingFileUrl={updateProofingFileUrl}',
  '              setUpdateProofingFileUrl={setUpdateProofingFileUrl}',
  '              handleUpdateOrderInfo={handleUpdateOrderInfo}',
  '              isUpdatingOrder={isUpdatingOrder}',
  '              setIsImageUploadDialogOpen={setIsImageUploadDialogOpen}',
  '              setImageViewerOpen={setImageViewerOpen}',
  '              setViewingImageUrl={setViewingImageUrl}',
  '            />',
  '',
  '            <DetailDesignsListCard',
  '              order={order}',
  '              editingQuantityDesignId={editingQuantityDesignId}',
  '              setEditingQuantityDesignId={setEditingQuantityDesignId}',
  '              inlineQuantityValue={inlineQuantityValue}',
  '              setInlineQuantityValue={setInlineQuantityValue}',
  '              handleUpdateDesignQuantity={handleUpdateDesignQuantity}',
  '              updatingDesignId={updatingDesignId}',
  '              setIsAddDesignDialogOpen={setIsAddDesignDialogOpen}',
  '              handleRemoveDesignClick={handleRemoveDesignClick}',
  '              setImageViewerOpen={setImageViewerOpen}',
  '              setViewingImageUrl={setViewingImageUrl}',
  '              setSelectedDesignForRelatedDies={setSelectedDesignForRelatedDies}',
  '              setIsRelatedDiesDialogOpen={setIsRelatedDiesDialogOpen}',
  '            />',
  '',
  '            <DetailPlateExportCard',
  '              order={order}',
  '              setIsPlateExportDialogOpen={setIsPlateExportDialogOpen}',
  '              setEditingPlateExport={setEditingPlateExport}',
  '              setIsHandToProductionDialogOpen={setIsHandToProductionDialogOpen}',
  '              setImageViewerOpen={setImageViewerOpen}',
  '              setViewingImageUrl={setViewingImageUrl}',
  '            />',
  '',
  '            {hasDieCutDesigns && (',
  '              <DetailDieExportCard',
  '                order={order}',
  '                hasDieCutDesigns={hasDieCutDesigns}',
  '                isDieExported={isDieExported}',
  '                setIsDieExportDialogOpen={setIsDieExportDialogOpen}',
  '                setIsReplaceDieDialogOpen={setIsReplaceDieDialogOpen}',
  '                setReplacingDieExport={setReplacingDieExport}',
  '                setIsAddDieDialogOpen={setIsAddDieDialogOpen}',
  '                handleRemoveDie={handleRemoveDie}',
  '                isRemovingDie={isRemovingDie}',
  '              />',
  '            )}',
  '          </div>',
  '        )}',
  '      </div>',
  '',
  '      <PrepressDetailDialogs',
  '        order={order}',
  '        isUploadDialogOpen={isUploadDialogOpen}',
  '        setIsUploadDialogOpen={setIsUploadDialogOpen}',
  '        uploadFiles={uploadFiles}',
  '        setUploadFiles={setUploadFiles}',
  '        uploadImage={uploadImage}',
  '        setUploadImage={setUploadImage}',
  '        handleUploadFiles={handleUploadFiles}',
  '        handleUploadImage={handleUploadImage}',
  '        isUploadingImage={isUploadingImage}',
  '        isImageUploadDialogOpen={isImageUploadDialogOpen}',
  '        setIsImageUploadDialogOpen={setIsImageUploadDialogOpen}',
  '        isConfirmRemoveDesignDialogOpen={isConfirmRemoveDesignDialogOpen}',
  '        setIsConfirmRemoveDesignDialogOpen={setIsConfirmRemoveDesignDialogOpen}',
  '        removeDesignTarget={removeDesignTarget}',
  '        handleConfirmRemoveDesign={handleConfirmRemoveDesign}',
  '        isRemovingDesign={isRemovingDesign}',
  '        imageViewerOpen={imageViewerOpen}',
  '        setImageViewerOpen={setImageViewerOpen}',
  '        viewingImageUrl={viewingImageUrl}',
  '        setViewingImageUrl={setViewingImageUrl}',
  '        isPlateExportDialogOpen={isPlateExportDialogOpen}',
  '        setIsPlateExportDialogOpen={setIsPlateExportDialogOpen}',
  '        editingPlateExport={editingPlateExport}',
  '        setEditingPlateExport={setEditingPlateExport}',
  '        handlePlateExportSuccess={handlePlateExportSuccess}',
  '        isDieExportDialogOpen={isDieExportDialogOpen}',
  '        setIsDieExportDialogOpen={setIsDieExportDialogOpen}',
  '        handleDieExportSuccess={handleDieExportSuccess}',
  '        isConfirmStatusChangeDialogOpen={isConfirmStatusChangeDialogOpen}',
  '        setIsConfirmStatusChangeDialogOpen={setIsConfirmStatusChangeDialogOpen}',
  '        nextStatusInfo={nextStatusInfo}',
  '        pendingStatus={pendingStatus}',
  '        setPendingStatus={setPendingStatus}',
  '        handleConfirmStatusChange={handleConfirmStatusChange}',
  '        isHandToProductionDialogOpen={isHandToProductionDialogOpen}',
  '        setIsHandToProductionDialogOpen={setIsHandToProductionDialogOpen}',
  '        hasDieCutDesigns={hasDieCutDesigns}',
  '        isDieExported={isDieExported}',
  '        handleConfirmHandToProduction={handleConfirmHandToProduction}',
  '        isHandingToProduction={isHandingToProduction}',
  '        isAddDesignDialogOpen={isAddDesignDialogOpen}',
  '        setIsAddDesignDialogOpen={setIsAddDesignDialogOpen}',
  '        availableDesignsForAdding={availableDesignsForAdding}',
  '        currentDesignForAdding={currentDesignForAdding}',
  '        addDesignsMutate={addDesignsMutate}',
  '        isAddingDesigns={isAddingDesigns}',
  '        isReplaceDieDialogOpen={isReplaceDieDialogOpen}',
  '        setIsReplaceDieDialogOpen={setIsReplaceDieDialogOpen}',
  '        replacingDieExport={replacingDieExport}',
  '        setReplacingDieExport={setReplacingDieExport}',
  '        selectedNewDieId={selectedNewDieId}',
  '        setSelectedNewDieId={setSelectedNewDieId}',
  '        replaceDieNotes={replaceDieNotes}',
  '        setReplaceDieNotes={setReplaceDieNotes}',
  '        dieSearchTerm={dieSearchTerm}',
  '        setDieSearchTerm={setDieSearchTerm}',
  '        handleReplaceDie={handleReplaceDie}',
  '        isReplacingDie={isReplacingDie}',
  '        availableDies={availableDies}',
  '        isLoadingDies={isLoadingDies}',
  '        isAddDieDialogOpen={isAddDieDialogOpen}',
  '        setIsAddDieDialogOpen={setIsAddDieDialogOpen}',
  '        selectedDieIdForAdd={selectedDieIdForAdd}',
  '        setSelectedDieIdForAdd={setSelectedDieIdForAdd}',
  '        addDieNotes={addDieNotes}',
  '        setAddDieNotes={setAddDieNotes}',
  '        addDieSearchTerm={addDieSearchTerm}',
  '        setAddDieSearchTerm={setAddDieSearchTerm}',
  '        handleAddDie={handleAddDie}',
  '        isAssigningDie={isAssigningDie}',
  '        availableDiesForAdd={availableDiesForAdd}',
  '        isLoadingAddDies={isLoadingAddDies}',
  '        isDieListDialogOpen={isDieListDialogOpen}',
  '        setIsDieListDialogOpen={setIsDieListDialogOpen}',
  '        isRelatedDiesDialogOpen={isRelatedDiesDialogOpen}',
  '        setIsRelatedDiesDialogOpen={setIsRelatedDiesDialogOpen}',
  '        selectedDesignForRelatedDies={selectedDesignForRelatedDies}',
  '        setSelectedDesignForRelatedDies={setSelectedDesignForRelatedDies}',
  '      />',
  '    </div>',
  '  );',
  '}',
  '',
];

const allLines = [...keepLines, ...newReturnLines];
const newContent = allLines.join('\n');

fs.writeFileSync(filePath, newContent, 'utf8');

console.log('Done! Original lines:', lines.length, '-> New lines:', allLines.length);
console.log('Removed', lines.length - allLines.length, 'lines (return JSX + RelatedDiesContent)');
